name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.0'
      
      - name: Release binaries and changelog
        uses: goreleaser/goreleaser-action@v6
        with:
          # https://goreleaser.com/customization/builds/go/
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        id: build-docker-image
        run: |
          COMMIT_TAG=$(basename "$GITHUB_REF")
          echo "Building tag: $COMMIT_TAG"

          docker build . -f Dockerfile \
            -t ${{secrets.DOCKERHUB_USERNAME}}/parallelhttp:$COMMIT_TAG \
            -t ${{secrets.DOCKERHUB_USERNAME}}/parallelhttp:latest
      
      - name: Dockerhub - Push the docker image
        id: push-docker-image
        run: |
          COMMIT_TAG=$(basename "$GITHUB_REF")
          echo "Pushing tag version: $COMMIT_TAG"

          docker push ${{secrets.DOCKERHUB_USERNAME}}/parallelhttp:$COMMIT_TAG
          docker push ${{secrets.DOCKERHUB_USERNAME}}/parallelhttp:latest
